export default {
    LOGIN_ACTION: "LOGIN_ACTION",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",
    LOGIN_ERROR: "LOGIN_ERROR",

    GET_SELF_ACTION: "GET_SELF_ACTION",
    GET_SELF_REQUEST: "GET_SELF_REQUEST",
    GET_SELF_RESPONSE: "GET_SELF_RESPONSE",
    GET_SELF_ERROR: "GET_SELF_ERROR"
}